services:
  web:
    build: ./web
    networks:
      - app-network

  api:
    build: ./api
    ports:
      - "$PORT_API:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mariadb:12
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:


